### ISSUE TITLE
Working with Oracle Advance Queues

### ISSUE THREAD

**Issue by sposnjak-cpot** [kubo/rust-oracle#52]
I am looking to hook up the my rust app to oracle database and we use AQ for communication. I can see in the bindings that there are functions for enq/deq and also for subscriptions, but can not find any examples on how to use them or any rust struct in form of a Queue. 

Is this not (yet) supported or am I missing something?

**Comment by kubo** [comment]
It has not been supported yet.
I tired it about three years ago and reported https://github.com/oracle/odpi/issues/104. I have not restarted it yet.

**Comment by kubo** [comment]
I added experimental advanced queuing support. See https://www.jiubao.org/rust-oracle/oracle/aq/index.html.
It is available when `aq_unstable` feature is enabled. It is unstable for the time being.

Add the following dependency in `Cargo.toml`:
```toml
[dependencies]
oracle = { git = "https://github.com/kubo/rust-oracle", features = ["aq_unstable"] }
```
